module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/EuJVmngGAsFEo4tj9eqOOO',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/39ppvc.jpg',
    NEWSLETTER_JID: '120363407516128480@g.us',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'MooN-X Bot',
    OWNER_NAME: 'MooN-X',
    OWNER_NUMBER: '919668738914',
    BOT_VERSION: '1.0.1',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ MooN-X',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb7HL5C0rGiUaquNz21g',
};
